
#Name Lists
[names]
# 地点列表
places = ["孤寂", "哀伤", "生息", "终焉", "富饶", "贪饕", "情欲", "怒焰", "傲慢", "怠惰", "妒忌", "暴食", "婪求", "贞洁", "节制", "慈悲", "勤勉", "坚忍", "仁善", "谦卑", "正义", "虔信", "渎神", "炽炎", "霜寒", "伟力", "狂喜", "漫游之欲", "光明", "永夜", "希望", "绝念", "荒芜", "丰穰", "不屈", "元能", "邪祟", "宿命", "磐石", "玄铁", "鎏金", "晶钻"]

# 形容词列表
adjectives = ["要塞", "城塞", "森林", "岛屿", "星球", "圣殿", "庭园", "高塔", "地牢", "城堡", "城邦", "王国", "山岳", "洞窟", "天柱", "墓园", "秘境", "藏书阁", "陵寝", "礼拜堂", "大教堂", "祭坛", "穹殿", "冥府", "囚狱", "忘川", "尖碑", "通天塔"]

	#Separator between places and adjectives
	separator = "的"
	#<Place> before <Adjective>
	order = true

#Button Position
[location]
	#X Coordinate for the button
	#Range: > 0
	x = 110
	#Y Coordinate for the button
	#Range: > 0
	y = 60

